[package]
name = "plur1bus"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "plur1bus"
path = "src/main.rs"

[dependencies]
plur1bus-rpc = { path = "../plur1bus-rpc" }
plur1bus-config = { path = "../plur1bus-config" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
gethostname = "0.5"
whoami = "1.5"
uuid = { version = "1", features = ["v4"] }
home = "0.5"
clap-markdown = "0.1"
sha2 = "0.10"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile.workspace = true
