// Shared by the native allow-list and Tauri's generated application ACL.
pub const SHELL_COMMANDS: &[&str] = &[
    "app_info",
    "settings_get",
    "settings_set",
    "connections_list",
    "connections_rename",
    "connections_remove",
    "pair_code",
    "pair_local",
    "open_connection",
    "autostart_get",
    "autostart_set",
    "quit_request",
    "quit_offer",
    "background_hint",
    "crash_offers",
    "crash_handled",
    "quit_response",
];

// Application manifest includes both trust zones; shell-ui still names only SHELL_COMMANDS.
pub const APP_COMMANDS: &[&str] = &[
    "app_info",
    "settings_get",
    "settings_set",
    "connections_list",
    "connections_rename",
    "connections_remove",
    "pair_code",
    "pair_local",
    "open_connection",
    "autostart_get",
    "autostart_set",
    "quit_request",
    "quit_offer",
    "background_hint",
    "crash_offers",
    "crash_handled",
    "quit_response",
    "shell_info",
];
