import { test } from 'node:test';
import assert from 'node:assert/strict';
import { inspect } from 'node:util';
import { ChatGPTPlan, HostIdentity, JwksVerifier, guardSiwc, chooseFailover, keyStatus, endpoint, profiles, importedProfile, credentialAccess, Sensitive, OpenAIError } from '../../src/openai-auth/index.ts';
import { FakeOpenAI, FakeRefreshOwner, MemorySecrets } from '../fixtures/openai/server.ts';
function setup() {
  const server = new FakeOpenAI(), store = new MemorySecrets(), owner = new FakeRefreshOwner(), events: unknown[] = [];
  const ports = { http: server, pkce: server, store, owner, clock: { now: () => server.now }, host: new HostIdentity(store, owner), verifier: new JwksVerifier(server, { now: () => server.now }), audit: (e: unknown) => { events.push(e); } };
  return { server, store, owner, events, ports, plan: new ChatGPTPlan(ports) };
}
const principal = { owner: 'owner', user: 'owner', agentOwner: 'owner', deployment: 'local' as const };
test('Acceptance 15: registration, OIDC, scope, PKCE, rotation, siwc and billing', async () => {
  const s = setup(); await s.plan.login('a', principal); await s.plan.login('a', principal);
  assert.equal(s.server.registrations.size, 1); s.server.account = 'account-b'; await s.plan.login('b', principal); assert.equal(s.server.registrations.size, 2);
  const old = JSON.parse(s.store.data.get(s.plan.accountRef('a'))!).refreshToken;
  s.server.now += 3_500_000; await Promise.all([s.plan.lease('a', principal), s.plan.lease('a', principal)]); assert.equal(s.server.refreshCount, 1);
  const reused = await s.server.request({ method: 'POST', url: s.server.issuer + '/token', form: { grant_type: 'refresh_token', refresh_token: old } }); assert.equal(reused.status, 400);
  await new ChatGPTPlan(s.ports).lease('a', principal); assert.equal(s.server.refreshCount, 1);
  await s.plan.models('a', principal); await s.plan.responses('a', principal, { model: 'fixture-model', input: 'hello' });
  const req = s.server.requests.find(r => r.url.endsWith('/responses'))!; assert.equal(req.json?.store, false); assert.equal(req.json?.stream, true);
  s.server.errorCode = 'subscription_sharing_usage_limit_exceeded'; await assert.rejects(s.plan.responses('a', principal, { model: 'fixture-model' }), { code: s.server.errorCode });
  assert.equal(chooseFailover('chatgpt_plan', [{ id: 'key', billing_path: 'api_key' }], [], s.server.errorCode), undefined);
  await s.plan.logout('a'); assert.equal(s.store.data.has(s.plan.accountRef('a')), false);
  for (const secret of s.server.secrets) assert.equal(JSON.stringify(s.events).includes(secret), false);
});
for (const badClaim of ['iss', 'aud', 'exp', 'nonce', 'signature'] as const) test('OIDC rejects ' + badClaim, async () => { const s = setup(); s.server.badClaim = badClaim; await assert.rejects(s.plan.login('a', principal), { code: 'id-token-invalid' }); assert.equal(s.store.data.has(s.plan.accountRef('a')), false); });
test('scope and state gates fail before persistence/inference', async () => { for (const flag of ['omitScope', 'badState'] as const) { const s = setup(); s.server[flag] = true; await assert.rejects(s.plan.login('a', principal)); assert.equal(s.store.data.has(s.plan.accountRef('a')), false); } });
test('host identity RFC 9278, stable, independent installs and JWKS cache', async () => { const s = setup(); const id = await s.ports.host.id(); assert.match(id, /^urn:ietf:params:oauth:jwk-thumbprint:sha-256:[A-Za-z0-9_-]{43}$/); assert.equal(await new HostIdentity(s.store, s.owner).id(), id); assert.notEqual(await new HostIdentity(new MemorySecrets(), new FakeRefreshOwner()).id(), id); await s.plan.login('a', principal); await s.plan.login('a', principal); assert.equal(s.server.jwksCount, 1); });
test('siwc closed wire guard refuses unsupported fields/tools/audio/system', () => {
  for (const field of ['background','conversation','max_output_tokens','metadata','prompt','prompt_cache_retention','safety_identifier','temperature','top_p','truncation','user','previous_response_id','audio']) assert.throws(() => guardSiwc({ model: 'test', [field]: true }), { code: 'siwc-unsupported' });
  for (const type of ['file_search','code_interpreter','image_generation','mcp','tool_search']) assert.throws(() => guardSiwc({ tools: [{ type }] }));
  for (const input of [[{ role: 'system', content: 'x' }], [{ role: 'user', content: [{ type: 'input_audio' }] }]]) assert.throws(() => guardSiwc({ input }));
  assert.deepEqual(guardSiwc({ instructions: 'x', store: true, stream: false }), { instructions: 'x', store: false, stream: true });
});
test('billing cross-path requires explicit policy and records decision', () => { const events: unknown[] = []; assert.equal(chooseFailover('api_key', [{ id: 'plan', billing_path: 'chatgpt_plan' }], []), undefined); assert.equal(chooseFailover('api_key', [{ id: 'plan', billing_path: 'chatgpt_plan' }], [{ from: 'api_key', to: 'chatgpt_plan' }], undefined, e => events.push(e)), 'plan'); assert.equal(events.length, 1); });
test('key expiry warnings, regional endpoints, owner-only plan', async () => { assert.equal(keyStatus(0, 1), 'auth-required'); assert.equal(keyStatus(3 * 86400000, 0), 'expires-3-days'); assert.equal(keyStatus(14 * 86400000, 0), 'expires-14-days'); for (const region of ['global','us','eu'] as const) assert.match(endpoint(region), new RegExp(region === 'global' ? '//api' : '//' + region)); await assert.rejects(setup().plan.login('a', { ...principal, user: 'other' }), { code: 'owner-only' }); await assert.rejects(setup().plan.login('a', { ...principal, deployment: 'hosted-multi-user' }), { code: 'owner-only' }); });
test('Acceptance 17: never-list port, disabled route 3, CLI label, source scan', async () => {
  const names = ['codex', ['open','claw'].join(''), 'hermes'];
  for (const os of ['posix', 'windows'] as const) for (const name of names) { let read = false; await assert.rejects(credentialAccess({ canonicalize: async () => os === 'windows' ? 'C:/USERS/TEST/.' + name + '/auth.json' : '/home/test/.' + name + '/auth.json', denied: async () => true }, 'ignored', async () => { read = true; })); assert.equal(read, false); }
  assert.equal(importedProfile('openai:chatgpt-oauth-restricted').enabled, false); assert.equal(profiles.codex.usage_label, 'personal/local only');
  const { readdir, readFile } = await import('node:fs/promises');
  for (const folder of ['openai-auth','voice']) for (const file of await readdir(new URL('../../src/' + folder + '/', import.meta.url))) { const src = await readFile(new URL('../../src/' + folder + '/' + file, import.meta.url), 'utf8'); assert.equal(src.includes(['app_', 'EMoamEEZ73f0CkXaXp7hrann'].join('')), false); assert.equal(src.includes(['CODEX_APP_SERVER','LOGIN_CLIENT_ID'].join('_')), false); }
});
test('secrets redact JSON, inspection, errors including hostile port failures', async () => { const s = setup(); const secret = s.server.secret(); const value = new Sensitive(secret); assert.equal(JSON.stringify(value).includes(secret), false); assert.equal(inspect(value).includes(secret), false); s.server.failPath = '/token'; await assert.rejects(s.plan.login('a', principal), e => { const text = inspect(e); for (const v of s.server.secrets) assert.equal(text.includes(v), false); return e instanceof OpenAIError; }); });
test('durable spent marker forbids refresh reuse after network failure and restart', async () => { const s = setup(); await s.plan.login('a', principal); s.server.now += 3500000; s.server.failPath = '/token'; await assert.rejects(s.plan.lease('a', principal)); s.server.failPath = undefined; const count = s.server.requests.length; await assert.rejects(new ChatGPTPlan(s.ports).lease('a', principal), { code: 'auth-required' }); assert.equal(s.server.requests.length, count); });
test('host corruption never silently regenerates installation key', async () => { const s = setup(); await s.store.set('openai.host.key', 'broken'); await assert.rejects(s.ports.host.id(), { code: 'persist-failed' }); assert.equal(await s.store.get('openai.host.key'), 'broken'); });
test('foreign store roots, aliases, casing, keychain and foreign registration metadata', async () => {
  const { createCredentialDenyPort, FOREIGN_CREDENTIAL_STORES } = await import('../../src/openai-auth/index.ts');
  for (const os of ['posix','windows'] as const) {
    const home = os === 'windows' ? 'C:/Users/Test' : '/home/test';
    const roots = FOREIGN_CREDENTIAL_STORES.map(s => home + '/.' + s.app);
    const deny = createCredentialDenyPort({ canonicalize: async p => p === 'alias' ? roots[0]! + '/auth.json' : p, roots, keychainItems: ['keychain:codex'], foreignRegistration: async p => p.endsWith('/foreign-registration') });
    for (const store of FOREIGN_CREDENTIAL_STORES) for (const suffix of store.suffixes) { const path = home + '/.' + store.app + '/' + suffix; assert.ok(await deny.denied(path)); assert.ok(await deny.denied(path.toUpperCase().replaceAll('/', '\\'))); }
    for (const path of ['alias','keychain:codex',home + '/foreign-registration']) { let opened = false; await assert.rejects(credentialAccess(deny, path, async () => { opened = true; })); assert.equal(opened, false); }
    assert.equal(await deny.denied(roots[0] + '-unrelated/auth.json'), false);
  }
});
test('API key expiry rejects before touching secret store and UI source constants', async () => { const { ApiKeyCredential, UI_TEXT } = await import('../../src/openai-auth/index.ts'); const store = new MemorySecrets(); let reads = 0; store.get = async () => { reads++; return 'synthetic'; }; await assert.rejects(new ApiKeyCredential(store, { now: () => 1 }, 'key', 0).lease(), { code: 'auth-required' }); assert.equal(reads, 0); assert.equal(UI_TEXT.button, 'Continue with ChatGPT'); assert.equal(UI_TEXT.usageUrl, 'https://chatgpt.com/settings/usage'); });
test('transfer moves account record and preserves remote host identity', async () => { const s = setup(); await s.plan.login('a', principal); const remote = new MemorySecrets(); const host = new HostIdentity(remote, new FakeRefreshOwner()); const before = await host.id(); await s.plan.transfer('a', { accept: async r => { await remote.set('openai.plan.a', r.value()); } }, principal); assert.equal(await host.id(), before); assert.equal(s.store.data.has('openai.plan.a'), false); assert.ok(remote.data.has('openai.plan.a')); });
test('callback localhost and reused authorization code refused', async () => { const s = setup(); s.server.redirect = async () => 'http://localhost:49152/auth/callback'; await assert.rejects(s.plan.login('a', principal), { code: 'invalid-request' }); const t = setup(); await t.plan.login('a', principal); const req = t.server.requests.find(r => r.form?.grant_type === 'authorization_code')!; assert.equal((await t.server.request(req)).status, 400); });
test('transport request and inference payload inspection never expose credentials', async () => { const s = setup(); await s.plan.login('a', principal); const result = await s.plan.responses('a', principal, { input: 'synthetic' }); for (const v of s.server.secrets) { assert.equal(JSON.stringify(s.server.requests).includes(v), false); assert.equal(inspect(s.server.requests).includes(v), false); assert.equal(JSON.stringify(result).includes(v), false); } });
test('refresh save failure never sends spent token again', async () => { const s = setup(); await s.plan.login('a', principal); s.server.now += 3500000; const save = s.store.set.bind(s.store); let writes = 0; s.store.set = async (r,v) => { if (++writes === 2) throw Error(s.server.secret()); await save(r,v); }; await assert.rejects(s.plan.lease('a', principal)); s.store.set = save; await assert.rejects(new ChatGPTPlan(s.ports).lease('a', principal), { code: 'auth-required' }); assert.equal(s.server.refreshCount, 1); });
test('all documented subscription-sharing errors retain typed codes without vendor messages', async () => { const { ERROR_CODES } = await import('../../src/openai-auth/index.ts'); const s = setup(); await s.plan.login('a', principal); for (const code of ERROR_CODES.filter(c => c.startsWith('subscription_sharing_'))) { s.server.errorCode = code; await assert.rejects(s.plan.responses('a', principal, {}), { code }); } });
test('host URN thumbprint matches exactly the persisted public JWK', async () => { const s = setup(); const id = await s.ports.host.id(); const { createHash } = await import('node:crypto'); const jwk = JSON.parse(s.store.data.get('openai.host.key')!); const expected = createHash('sha256').update(JSON.stringify({ crv: jwk.crv, kty: jwk.kty, x: jwk.x })).digest('base64url'); assert.equal(id.split(':').at(-1), expected); });
test('ten-minute deadline rejects a hung PKCE port and closes it', async () => { const s = setup(); let deadline = 0, closed = false; const abort = new AbortController(); s.server.close = async () => { closed = true; }; s.server.authorize = async () => { abort.abort(); return new Promise<string>(() => {}); }; const plan = new ChatGPTPlan({ ...s.ports, deadline: ms => { deadline = ms; return abort.signal; } }); await assert.rejects(plan.login('a', principal)); assert.equal(deadline, 600000); assert.ok(closed); });
