import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { defaults, validate } from '@plur1bus/config-schema';
import { createSecretStore, createMemoryBackend, createMemoryAuditSink } from '../../src/secrets/index.ts';
import { createOpenAIRuntime } from '../../src/openai-auth/runtime.ts';
import { composeAuth, billingClassOf, type ProviderDefinition } from '../../src/composition/auth.ts';
import { createTurnProvider } from '../../src/composition/provider.ts';
import { ToolRegistry } from '../../src/tools/registry.ts';
import { createCallBudget, PriceBook, SHIPPED_PRICE_TABLES } from '../../src/budget/index.ts';
import type { CompositionDeps } from '../../src/composition/index.ts';
import { localOpenAI } from './local-server.ts';
const principal = { owner: 'owner', user: 'owner', agentOwner: 'owner', deployment: 'local' as const };
test('local HTTP: real PKCE login → composed Responses turn → plan units and existing budget; plan limit never falls back', async () => {
  const local = await localOpenAI(), home = await mkdtemp(join(tmpdir(), 'd110-turn-')), config = defaults(), audit: unknown[] = [];
  const secrets = createSecretStore({ keyring: createMemoryBackend(), file: createMemoryBackend(), fileFallback: () => false, audit: createMemoryAuditSink() });
  const logger = { info: (...v: unknown[]) => { audit.push(v); }, warn: (...v: unknown[]) => { audit.push(v); } };
  const egress = { decide: async () => { throw Error('DNS forbidden'); } };
  const runtime = createOpenAIRuntime({ home, config: () => config, secrets, egress, options: { fetch: local.transport }, clock: () => local.fake.now, audit: { append: (e: unknown) => { audit.push(e); } }, logger } as unknown as CompositionDeps);
  const budget = createCallBudget({ path: join(home, 'budget.sqlite'), clock: { now: () => local.fake.now }, prices: new PriceBook(SHIPPED_PRICE_TABLES) });
  try {
    const login = await runtime.auth.startLogin({ principal }); await local.authorize(login.authorizeUrl); const credential = await runtime.auth.awaitLogin(login.loginId, principal);
    const definition: ProviderDefinition = { profile: { id: 'openai:chatgpt-plan', display_name: 'ChatGPT plan', kind: 'oauth_pkce', capabilities: ['chat'], auth_header_scheme: 'Authorization: Bearer {token}', client_registration: 'dynamic_on_authorize', policy_status: 'allowed', policy_source: 'D110', policy_checked: '2026-10-08' }, entries: [], openai: { credentialId: credential.id, person: 'owner' }, wireFormat: 'codex_responses', billingPath: 'plan', defaultModel: 'fixture-model' };
    assert.equal(billingClassOf({ ...definition, billingPath: 'paid' }), 'plan', 'dynamic ChatGPT registration always bills the plan');
    config.modelProfiles.default = { strategy: 'fallback', candidates: [{ model: 'plan/fixture-model', weight: 1 }], params: {}, cache: { hint: 'none' } };
    const auth = composeAuth({ config, definitions: { plan: definition }, secrets, egress: egress as never, fetch: local.transport, openai: runtime });
    const provider = createTurnProvider({ profiles: auth.profiles, billing: auth.billing, family: auth.families, budget, registry: new ToolRegistry(), grants: { get: () => undefined, list: () => [] }, approval: { request: async () => ({ approved: false }) }, log: r => { audit.push(r); }, resultStore: { put: async () => 'unused' } });
    const request = { sessionId: 'session-a', turnId: 'turn-a', agentId: 'agent-a', principal: 'owner', authenticatedPerson: 'owner', summaries: [], memory: '', messages: [{ role: 'user' as const, text: 'hello' }], signal: new AbortController().signal };
    const chunks = []; for await (const chunk of provider.stream(request)) chunks.push(chunk);
    assert.equal(chunks.filter(c => c.type === 'delta').map(c => c.text).join(''), 'plan answer');
    assert.deepEqual(runtime.usage.total('owner'), { unit: 'plan_tokens', inputTokens: 100, outputTokens: 10, calls: 1 });
    assert.equal(auth.billing.plan, 'plan');
    const { DatabaseSync } = await import('node:sqlite'); const db = new DatabaseSync(join(home, 'budget.sqlite')); const row = db.prepare('SELECT input_tokens,output_tokens,cost_micros FROM usage_event').get(); db.close(); assert.deepEqual({ ...row }, { input_tokens: 100, output_tokens: 10, cost_micros: null });
    assert.equal(local.bodies[0]!.store, false); assert.equal(local.bodies[0]!.stream, true); assert.equal('max_output_tokens' in local.bodies[0]!, false);
    local.fake.errorCode = 'subscription_sharing_usage_limit_exceeded';
    await assert.rejects(async () => { for await (const _ of provider.stream({ ...request, turnId: 'turn-b' })) {} }, { code: 'subscription_sharing_usage_limit_exceeded', retryAfterMs: 12000 });
    assert.equal(local.responses(), 2);
    for (const secret of local.fake.secrets) assert.equal(JSON.stringify([audit, chunks, runtime.auth]).includes(secret), false);
    await assert.rejects(async () => { for await (const _ of provider.stream({ ...request, authenticatedPerson: 'other' })) {} });
    const deniedDb = new DatabaseSync(join(home, 'budget.sqlite')); assert.equal((deniedDb.prepare('SELECT COUNT(*) AS n FROM usage_event').get() as { n: number }).n, 1, 'a locally refused auth attempt has no billable usage'); deniedDb.close();
    assert.throws(() => runtime.adapter({ ...definition, wireFormat: 'chat_completions' }), { code: 'siwc-unsupported' });
    auth.close();
  } finally { budget.close(); await runtime.close(); await local.close(); await rm(home, { recursive: true, force: true }); }
});
test('auth config has bounded defaults, closed keys and rejects two federated sources', () => {
  const cfg = defaults(); assert.equal(cfg.auth?.openai.liveHandleTtlSeconds, 60);
  assert.equal(validate({ ...cfg, auth: { openai: { liveHandleTtlSeconds: 601 } } }).ok, false);
  assert.equal(validate({ ...cfg, auth: { openai: { federated: { command: 'binary', file: 'token' } } } }).ok, false);
});
