// Generates docs/rpc.md (from packages/rpc-schema/schema/rpc.schema.json) and docs/cli.md (from the clap
// definitions via the hidden `plur1bus __markdown` subcommand). `--check` compares instead of writing and
// exits 1 when either file is stale; CI runs it as `pnpm docs:check`.
//
// The binary is $PLUR1BUS_BIN, default target/debug/plur1bus(.exe) under the repo root; `pnpm docs:gen` and
// `pnpm docs:check` build it first. The comparison ignores CRLF vs LF so a Windows checkout with
// core.autocrlf does not read as stale.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const check = process.argv.includes("--check");
const schema = JSON.parse(readFileSync(new URL("packages/rpc-schema/schema/rpc.schema.json", root), "utf8"));
const fence = (v) => "```json\n" + JSON.stringify(v, null, 2) + "\n```";
const stabilityLine = (def) => {
  let line = `**Stability:** ${def["x-stability"]} · since ${def["x-since"]}`;
  if (def["x-deprecated"]) {
    const { since, removeAfter, replacement } = def["x-deprecated"];
    line += ` · **deprecated** since ${since}, removal not before ${removeAfter}; use ${replacement}`;
  }
  return line;
};

let rpc = `# RPC reference (rpc ${schema["x-rpc-version"]})

Generated from \`packages/rpc-schema/schema/rpc.schema.json\` by \`scripts/gen-docs.mjs\` — do not edit by hand; run \`pnpm docs:gen\`.
JSON-RPC 2.0, one JSON value per line (NDJSON, max 4 MiB per line), on \`run/core.sock\` (POSIX) or the per-home named pipe
(Windows). The first call on a connection is \`core.auth\`; its result carries \`contract\` (engine contract version) and \`rpc\`
(this schema's version). Design and rationale: \`docs/adr/ADR-012-process-model-and-languages.md\`.
${schema.description ? `\n${schema.description}\n` : ""}
## Error codes

A closed enum; the core puts the code into every error response as \`error.data.error\`, with optional \`reason\`, \`detail\` and \`ids\` (a map of non-secret ids a caller needs to recover, e.g. after a half-finished shared-copy refresh).

${schema.$defs.ErrorCode.enum.map((e) => `- \`${e}\``).join("\n")}

## Stability

${Object.entries(schema.$defs.methods).filter(([, d]) => d["x-stability"] === "stable").map(([n]) => `- \`${n}\``).join("\n")}
${Object.entries(schema.$defs.notifications).filter(([, d]) => d["x-stability"] === "stable").map(([n]) => `- \`${n}\` (notification)`).join("\n")}

Everything else is experimental and may change in any minor release (ADR-016 §4).

## Methods
`;
for (const [name, def] of Object.entries(schema.$defs.methods)) {
  const desc = def.description ?? def.params?.description ?? "";
  rpc += `\n### \`${name}\`\n\n${stabilityLine(def)}\n\n${desc ? `${desc}\n\n` : ""}**params**\n\n${fence(def.params)}\n\n**result**\n\n${fence(def.result)}\n`;
}
rpc += `\n## Notifications\n\nDelivered on the same connection to clients that called \`events.subscribe\`.\n`;
for (const [name, def] of Object.entries(schema.$defs.notifications)) {
  rpc += `\n### \`${name}\`\n\n${stabilityLine(def)}\n\n${def.description ? `${def.description}\n\n` : ""}${fence(def)}\n`;
}
rpc += `\n## Definitions\n\nShared \`$defs\` referenced above as \`#/$defs/<Name>\`.\n`;
for (const [name, def] of Object.entries(schema.$defs)) {
  if (name === "methods" || name === "notifications") continue;
  rpc += `\n### \`${name}\`\n\n${fence(def)}\n`;
}

const defaultBin = fileURLToPath(new URL(`target/debug/plur1bus${process.platform === "win32" ? ".exe" : ""}`, root));
const bin = process.env.PLUR1BUS_BIN ?? defaultBin;
const cli = `# CLI reference

Generated by \`scripts/gen-docs.mjs\` from the clap definitions (\`plur1bus __markdown\`) — do not edit by hand; run \`pnpm docs:gen\`.
Every command accepts \`--json\` (machine-readable output: the raw RPC result or a stable object, on stdout) and \`--home <path>\`.
Commands marked H2, M2, M3, M4, M1b-3 or M8 are stubs that name the milestone delivering them and exit 2.

` + execFileSync(bin, ["__markdown"], { encoding: "utf8" });

const lf = (s) => s.replace(/\r\n/g, "\n");
let stale = 0;
for (const [path, content] of [["docs/rpc.md", rpc], ["docs/cli.md", cli]]) {
  const url = new URL(path, root);
  if (check) {
    let cur = "";
    try { cur = readFileSync(url, "utf8"); } catch { /* missing counts as stale */ }
    if (lf(cur) !== lf(content)) { console.error(`stale: ${path} (run pnpm docs:gen)`); stale += 1; }
  } else writeFileSync(url, lf(content));
}
if (stale) process.exit(1);
console.log(check ? "docs up to date" : "docs written");
