// The settings catalogue behind the palette's "Settings" group: a static subset of `packages/config-schema/schema/config.schema.json`
// (the schema of config.json, `config.get` / `config.set` in docs/rpc.md; docs/config.md for the tiers). The schema package is NOT
// imported: it pulls ajv and Node code, and the bundle must not. test/palette-index.test.ts reads the schema file and fails when
// this list drifts from it (a key added, removed, or its tier or help changed), so regenerate the rows when it does.
//
// What is real: key, type, tier and help text, all copied from the schema. A key is listed when it is a leaf or carries an
// `x-tier` (objects such as `agents` or `modules` are edited as a whole). `help` is the node's own `description`, else its nearest
// ancestor's (so `metrics.port` carries the description of `metrics`). `$schema` and `schemaVersion` are not settings.
// What is NOT available: localised labels. The schema has no titles, so the label is derived from the last key segment
// (`softBudgetMs` -> "Soft budget ms") and help stays in the schema's English. A localised catalogue needs schema titles or an
// owner-approved UI catalogue (follow-up).
export type SettingSpec = { readonly key: string; readonly type: string; readonly tier: "basic" | "advanced"; readonly help?: string };

export const SETTINGS: readonly SettingSpec[] = [
  { key: "core.logLevel", type: "enum", tier: "advanced", help: "Minimum severity written to the core log." },
  { key: "core.recall.softBudgetMs", type: "integer", tier: "advanced", help: "Soft target duration for a recall, in milliseconds." },
  { key: "core.recall.hardBudgetMs", type: "integer", tier: "advanced", help: "Maximum duration allowed for a recall before it is aborted, in milliseconds." },
  { key: "core.recall.capChars", type: "integer", tier: "advanced", help: "Maximum number of characters returned by a recall." },
  { key: "core.capture.waitMs", type: "integer", tier: "advanced", help: "Maximum time to wait for a memory capture, in milliseconds." },
  { key: "core.shutdownBudgetMs", type: "integer", tier: "advanced", help: "Maximum time the core spends on graceful shutdown, in milliseconds." },
  { key: "supervisor.graceMs", type: "integer", tier: "advanced", help: "Grace period given to a child process to exit during shutdown, in milliseconds." },
  { key: "supervisor.healthIntervalMs", type: "integer", tier: "advanced", help: "Interval between child-process health checks, in milliseconds." },
  { key: "metrics.enabled", type: "boolean", tier: "advanced", help: "Whether to expose the read-only Prometheus metrics endpoint." },
  { key: "metrics.port", type: "integer", tier: "advanced", help: "Loopback port used by the metrics endpoint." },
  { key: "logs.maxBytes", type: "integer", tier: "advanced", help: "Maximum size of each log file before rotation, in bytes." },
  { key: "logs.keep", type: "integer", tier: "advanced", help: "Number of rotated log files to retain." },
  { key: "agents", type: "object", tier: "basic", help: "Per-agent settings keyed by a lowercase agent identifier." },
  { key: "extensions.allowUnsigned", type: "boolean", tier: "advanced", help: "Whether unsigned extension packages may be installed." },
  { key: "extensions.trashDays", type: "integer", tier: "advanced", help: "Number of days uninstalled extensions are retained in the trash." },
  { key: "extensions.limits.packageBytes", type: "integer", tier: "advanced", help: "Maximum size of an extension package, in bytes." },
  { key: "extensions.limits.skillBytes", type: "integer", tier: "advanced", help: "Maximum size of an installed skill folder, in bytes." },
  { key: "embedding.useClass", type: "enum", tier: "basic", help: "Intended use of the embedding model: general, research, or commercial." },
  { key: "embedding.acceptedNcLicence", type: "boolean", tier: "advanced", help: "Whether the owner has accepted the model's non-commercial licence terms." },
  { key: "embedding.acceptedNcLicenceAt", type: "string", tier: "advanced", help: "Date-time when the non-commercial licence was accepted." },
  { key: "engine", type: "object", tier: "advanced", help: "Pass-through to the engine's EngineConfig (57 keys, see docs/config-engine-keys.md). Every key here is class core until the engine declares readAt: live (engine PR E5)." },
  { key: "engine.baseDbPathOverride", type: "string", tier: "advanced", help: "Testing/advanced only; default <home>/state/lancedb" },
  { key: "providers", type: "object", tier: "basic", help: "Reserved namespace for model-provider configuration." },
  { key: "auth.openai.loopbackTimeoutMs", type: "integer", tier: "advanced", help: "Loopback login deadline." },
  { key: "auth.openai.httpTimeoutMs", type: "integer", tier: "advanced", help: "Bounded OpenAI HTTP deadline." },
  { key: "auth.openai.refreshSkewSeconds", type: "integer", tier: "advanced", help: "Refresh before expiration, plus up to 15 seconds of jitter." },
  { key: "auth.openai.liveHandleTtlSeconds", type: "integer", tier: "advanced", help: "GPT-Live Harness handle redemption lifetime." },
  { key: "auth.openai.voiceDailySeconds", type: "integer", tier: "advanced", help: "Per-person and per-agent daily voice ceiling." },
  { key: "auth.openai.voiceCapacity", type: "integer", tier: "advanced", help: "Maximum concurrent voice sessions, no greater than the provider tier." },
  { key: "auth.openai.clientRegistration", type: "string", tier: "advanced", help: "OpenAI-issued registration per person and workspace; no borrowed client IDs." },
  { key: "auth.openai.storeBackend", type: "string", tier: "advanced", help: "Use the existing secret service. auto permits only its explicitly enabled encrypted-file fallback." },
  { key: "auth.openai.federated", type: "object", tier: "advanced", help: "External bearer supplier: one executable or file, explicit arguments and environment." },
  { key: "auth.openai.federated.command", type: "string", tier: "advanced", help: "Executable that prints a fresh federated token as JSON on stdout (run without a shell). Mutually exclusive with file." },
  { key: "auth.openai.federated.file", type: "string", tier: "advanced", help: "File holding the federated token and its expiry, re-read on refresh. Mutually exclusive with command." },
  { key: "auth.openai.federated.args", type: "array", tier: "advanced", help: "Arguments passed to command, one array element per argument (no shell interpolation)." },
  { key: "auth.openai.federated.environment", type: "object", tier: "advanced", help: "Extra environment variables for command; only these and the built-in allowlist are passed." },
  { key: "oauth", type: "object", tier: "advanced", help: "Reserved namespace for OAuth configuration." },
  { key: "decision", type: "object", tier: "advanced", help: "Reserved namespace for decision model configuration." },
  { key: "modelRoles", type: "object", tier: "basic", help: "Model identifiers assigned to the supported functional roles." },
  { key: "modelProfiles", type: "object", tier: "advanced", help: "Named model profiles (C4): an ordered candidate list with weights for fallback or mixture-of-agents (moa) use, plus sampling parameters and cache hints. Data only; selection is the router's job. List order is priority order." },
  { key: "models.scan.enabled", type: "boolean", tier: "advanced", help: "Whether periodic model discovery scans are enabled." },
  { key: "models.scan.intervalHours", type: "integer", tier: "advanced", help: "Hours between periodic model discovery scans." },
  { key: "secrets.fileFallback.enabled", type: "boolean", tier: "advanced", help: "Use the encrypted file store (AES-256-GCM, machine-bound key file next to it) when the OS keyring is unavailable. Off until the owner decides ADR-005 Q3." },
  { key: "egress.allowHosts", type: "array", tier: "advanced", help: "Exact names, `*.suffix` (subdomains of any depth, not the apex), `*` (any name, never an IP literal) or an exact canonical IP literal (IPv6 in brackets)." },
  { key: "egress.allowPorts", type: "array", tier: "advanced", help: "Destination ports allowed for outgoing requests." },
  { key: "egress.allowLoopback", type: "boolean", tier: "advanced", help: "Allow http(s) to loopback hosts (localhost, 127.0.0.0/8, ::1) that are also listed in allowHosts. A public name that resolves to loopback stays refused." },
  { key: "voice.providers.elevenlabs.enabled", type: "boolean", tier: "advanced", help: "Whether ElevenLabs may be used. Off until enabled and given an apiKeyRef." },
  { key: "voice.providers.elevenlabs.apiKeyRef", type: "string", tier: "advanced", help: "Secret-store reference holding the ElevenLabs API key." },
  { key: "voice.providers.elevenlabs.region", type: "enum", tier: "advanced", help: "Data-residency region: default (global), us, eu or in. Ignored when baseUrl is set." },
  { key: "voice.providers.elevenlabs.baseUrl", type: "string", tier: "advanced", help: "Override of the API base URL (https only, or loopback for a local relay)." },
  { key: "voice.providers.elevenlabs.defaultVoice", type: "string", tier: "advanced", help: "Voice id used when a request names none." },
  { key: "voice.providers.elevenlabs.defaultModel", type: "string", tier: "advanced", help: "Text-to-speech model id used when a request names none; discovery lists the available ones." },
  { key: "voice.providers.elevenlabs.defaultSttModel", type: "string", tier: "advanced", help: "Speech-to-text model id used when a request names none." },
  { key: "voice.providers.elevenlabs.zeroRetention", type: "boolean", tier: "advanced", help: "Ask ElevenLabs not to log or retain request content (enable_logging=false), where the account plan allows it." },
  { key: "voice.providers.xai.enabled", type: "boolean", tier: "advanced", help: "Whether Grok Voice may be used. Off until enabled and given an apiKeyRef." },
  { key: "voice.providers.xai.apiKeyRef", type: "string", tier: "advanced", help: "Secret-store reference holding the xAI API key." },
  { key: "voice.providers.xai.baseUrl", type: "string", tier: "advanced", help: "Override of the API base URL (https only, or loopback for a local relay)." },
  { key: "voice.providers.xai.defaultVoice", type: "string", tier: "advanced", help: "Voice used when a session names none." },
  { key: "voice.providers.xai.defaultModel", type: "string", tier: "advanced", help: "Realtime model id used when a session names none; found by discovery when empty." },
  { key: "voice.providers.gemini.enabled", type: "boolean", tier: "advanced", help: "Whether Gemini Live may be used. Off until enabled and given an apiKeyRef." },
  { key: "voice.providers.gemini.apiKeyRef", type: "string", tier: "advanced", help: "Secret-store reference holding the Gemini API key." },
  { key: "voice.providers.gemini.baseUrl", type: "string", tier: "advanced", help: "Override of the API base URL (https only, or loopback for a local relay)." },
  { key: "voice.providers.gemini.defaultVoice", type: "string", tier: "advanced", help: "Prebuilt voice name used when a session names none." },
  { key: "voice.providers.gemini.defaultModel", type: "string", tier: "advanced", help: "Live model id used when a session names none; native-audio models are found by discovery when empty." },
  { key: "voice.providers.polly.enabled", type: "boolean", tier: "advanced", help: "Whether Polly may be used. Off until enabled." },
  { key: "voice.providers.polly.region", type: "string", tier: "advanced", help: "AWS region for Polly; the SDK's own default applies when empty." },
  { key: "voice.providers.polly.credentials.profile", type: "string", tier: "advanced", help: "Name of the AWS shared-config profile (including SSO profiles); the default chain applies when empty." },
  { key: "voice.providers.polly.defaultVoice", type: "string", tier: "advanced", help: "Voice id used when a request names none." },
  { key: "voice.providers.polly.defaultModel", type: "string", tier: "advanced", help: "Polly engine (standard, neural, long-form, generative) used when a request names none." },
  { key: "voice.local.language", type: "string", tier: "advanced", help: "Language of the local voice (catalog code such as de or en). Empty: the system language when the catalog has it, else en." },
  { key: "voice.local.profile", type: "enum", tier: "advanced", help: "Local model tier: fast (streaming recogniser, small voice) or quality (larger models)." },
  { key: "voice.local.perAgent", type: "object", tier: "advanced", help: "Per-agent override of language and tier, keyed by agent identifier." },
  { key: "voice.local.catalogOverride", type: "object", tier: "advanced", help: "Data that adds or replaces catalog models and languages (adding a language is data, not code). Same shape as the built-in catalog." },
  { key: "voice.local.modelsDir", type: "string", tier: "advanced", help: "Directory for downloaded voice models. Empty: a directory under the harness data directory." },
  { key: "voice.local.acceptNcLicence", type: "boolean", tier: "advanced", help: "Confirm that models under non-commercial or unconfirmed licences may be downloaded and used. Off by default; the licence text is shown first." },
  { key: "voice.localRealtime.enabled", type: "boolean", tier: "advanced", help: "Whether the local real-time profile applies. When off, every feature runs without a time budget." },
  { key: "voice.localRealtime.endpointingMs", type: "integer", tier: "advanced", help: "Silence after speech, in milliseconds, before the user's turn counts as finished." },
  { key: "voice.localRealtime.speculativeTurnStart", type: "boolean", tier: "advanced", help: "Start the agent turn on the final transcript before the silence window ends, and cancel it if the user keeps talking." },
  { key: "voice.localRealtime.ackSound", type: "boolean", tier: "advanced", help: "Play a short acknowledgement sound when the user's turn ends." },
  { key: "voice.localRealtime.sentenceChunking.maxWords", type: "integer", tier: "advanced", help: "Maximum words in one spoken chunk; longer sentences are cut at a comma when possible." },
  { key: "voice.localRealtime.features.autoRecall", type: "object", tier: "advanced", help: "Automatic memory recall before the answer." },
  { key: "voice.localRealtime.features.autoRecall.mode", type: "enum", tier: "advanced", help: "on: runs before the answer within maxMs; deferred: runs after the turn; off: does not run." },
  { key: "voice.localRealtime.features.autoRecall.maxMs", type: "integer", tier: "advanced", help: "Time budget in milliseconds for an on feature; the feature is skipped when it takes longer." },
  { key: "voice.localRealtime.features.reranker", type: "object", tier: "advanced", help: "Reranking of recalled memories." },
  { key: "voice.localRealtime.features.reranker.mode", type: "enum", tier: "advanced", help: "on: runs before the answer within maxMs; deferred: runs after the turn; off: does not run." },
  { key: "voice.localRealtime.features.reranker.maxMs", type: "integer", tier: "advanced", help: "Time budget in milliseconds for an on feature; the feature is skipped when it takes longer." },
  { key: "voice.localRealtime.features.recallMultiIdentity", type: "object", tier: "advanced", help: "Recall across several linked identities." },
  { key: "voice.localRealtime.features.recallMultiIdentity.mode", type: "enum", tier: "advanced", help: "on: runs before the answer within maxMs; deferred: runs after the turn; off: does not run." },
  { key: "voice.localRealtime.features.recallMultiIdentity.maxMs", type: "integer", tier: "advanced", help: "Time budget in milliseconds for an on feature; the feature is skipped when it takes longer." },
  { key: "voice.localRealtime.features.promptEnrichment", type: "object", tier: "advanced", help: "Prompt enrichment with short context." },
  { key: "voice.localRealtime.features.promptEnrichment.mode", type: "enum", tier: "advanced", help: "on: runs before the answer within maxMs; deferred: runs after the turn; off: does not run." },
  { key: "voice.localRealtime.features.promptEnrichment.maxMs", type: "integer", tier: "advanced", help: "Time budget in milliseconds for an on feature; the feature is skipped when it takes longer." },
  { key: "voice.localRealtime.features.decisionService", type: "object", tier: "advanced", help: "Decision-model call before the answer." },
  { key: "voice.localRealtime.features.decisionService.mode", type: "enum", tier: "advanced", help: "on: runs before the answer within maxMs; deferred: runs after the turn; off: does not run." },
  { key: "voice.localRealtime.features.decisionService.maxMs", type: "integer", tier: "advanced", help: "Time budget in milliseconds for an on feature; the feature is skipped when it takes longer." },
  { key: "voice.localRealtime.features.postTurnRefine", type: "object", tier: "advanced", help: "Refinement work after the answer has been spoken." },
  { key: "voice.localRealtime.features.postTurnRefine.mode", type: "enum", tier: "advanced", help: "on: runs before the answer within maxMs; deferred: runs after the turn; off: does not run." },
  { key: "voice.localRealtime.features.postTurnRefine.maxMs", type: "integer", tier: "advanced", help: "Time budget in milliseconds for an on feature; the feature is skipped when it takes longer." },
  { key: "voice.localRealtime.features.memoryWrite", type: "object", tier: "advanced", help: "Memory capture of the turn." },
  { key: "voice.localRealtime.features.memoryWrite.mode", type: "enum", tier: "advanced", help: "on: runs before the answer within maxMs; deferred: runs after the turn; off: does not run." },
  { key: "voice.localRealtime.features.memoryWrite.maxMs", type: "integer", tier: "advanced", help: "Time budget in milliseconds for an on feature; the feature is skipped when it takes longer." },
  { key: "voice.localRealtime.features.compaction", type: "object", tier: "advanced", help: "Conversation compaction." },
  { key: "voice.localRealtime.features.compaction.mode", type: "enum", tier: "advanced", help: "on: runs before the answer within maxMs; deferred: runs after the turn; off: does not run." },
  { key: "voice.localRealtime.features.compaction.maxMs", type: "integer", tier: "advanced", help: "Time budget in milliseconds for an on feature; the feature is skipped when it takes longer." },
  { key: "voice.localRealtime.toolSchemas", type: "enum", tier: "advanced", help: "Tool schemas given to the model in real-time turns: reduced (smaller prompt, faster) or full." },
  { key: "voice.localRealtime.auditDetail", type: "enum", tier: "advanced", help: "Detail of the audit record for real-time turns: minimal or full." },
  { key: "voice.localRealtime.perAgent", type: "object", tier: "advanced", help: "Per-agent override of any localRealtime key (same shape, no defaults), keyed by agent identifier." },
  { key: "modules", type: "object", tier: "advanced", help: "Per-module settings, keyed by module name (B13). A change restarts only that module; `enabled: false` keeps it stopped." },
  { key: "media.adapters.openai.enabled", type: "boolean", tier: "advanced", help: "Unset: on once `apiKeyRef` resolves to a secret. `false` keeps the adapter off whatever the key." },
  { key: "media.adapters.openai.apiKeyRef", type: "string", tier: "advanced", help: "Name of the secret that holds the API key (a handle, never the key itself). Store the key with `plur1bus secret set <name>`, value on stdin." },
  { key: "media.adapters.openai.baseUrl", type: "string", tier: "advanced", help: "Override the provider endpoint (an absolute http(s) URL, checked when the adapter is built). https only; plain http is accepted for loopback test servers." },
  { key: "media.adapters.openai.model", type: "string", tier: "advanced", help: "Model identifier sent to the provider." },
  { key: "media.adapters.openai.timeoutMs", type: "integer", tier: "advanced", help: "Upper bound for one generation, including polling, in milliseconds." },
  { key: "media.adapters.openai.maxConcurrent", type: "integer", tier: "advanced", help: "How many requests this adapter runs at once; further jobs wait." },
  { key: "media.adapters.google.enabled", type: "boolean", tier: "advanced", help: "Unset: on once `apiKeyRef` resolves to a secret. `false` keeps the adapter off whatever the key." },
  { key: "media.adapters.google.apiKeyRef", type: "string", tier: "advanced", help: "Name of the secret that holds the API key (a handle, never the key itself). Store the key with `plur1bus secret set <name>`, value on stdin." },
  { key: "media.adapters.google.baseUrl", type: "string", tier: "advanced", help: "Override the provider endpoint (an absolute http(s) URL, checked when the adapter is built). https only; plain http is accepted for loopback test servers." },
  { key: "media.adapters.google.model", type: "string", tier: "advanced", help: "Model identifier sent to the provider." },
  { key: "media.adapters.google.timeoutMs", type: "integer", tier: "advanced", help: "Upper bound for one generation, including polling, in milliseconds." },
  { key: "media.adapters.google.maxConcurrent", type: "integer", tier: "advanced", help: "How many requests this adapter runs at once; further jobs wait." },
  { key: "media.adapters.xai.enabled", type: "boolean", tier: "advanced", help: "Unset: on once `apiKeyRef` resolves to a secret. `false` keeps the adapter off whatever the key." },
  { key: "media.adapters.xai.apiKeyRef", type: "string", tier: "advanced", help: "Name of the secret that holds the API key (a handle, never the key itself). Store the key with `plur1bus secret set <name>`, value on stdin." },
  { key: "media.adapters.xai.baseUrl", type: "string", tier: "advanced", help: "Override the provider endpoint (an absolute http(s) URL, checked when the adapter is built). https only; plain http is accepted for loopback test servers." },
  { key: "media.adapters.xai.model", type: "string", tier: "advanced", help: "Model identifier sent to the provider." },
  { key: "media.adapters.xai.timeoutMs", type: "integer", tier: "advanced", help: "Upper bound for one generation, including polling, in milliseconds." },
  { key: "media.adapters.xai.maxConcurrent", type: "integer", tier: "advanced", help: "How many requests this adapter runs at once; further jobs wait." },
  { key: "media.adapters.openrouter.enabled", type: "boolean", tier: "advanced", help: "Unset: on once `apiKeyRef` resolves to a secret. `false` keeps the adapter off whatever the key." },
  { key: "media.adapters.openrouter.apiKeyRef", type: "string", tier: "advanced", help: "Name of the secret that holds the API key (a handle, never the key itself). Store the key with `plur1bus secret set <name>`, value on stdin." },
  { key: "media.adapters.openrouter.baseUrl", type: "string", tier: "advanced", help: "Override the provider endpoint (an absolute http(s) URL, checked when the adapter is built). https only; plain http is accepted for loopback test servers." },
  { key: "media.adapters.openrouter.model", type: "string", tier: "advanced", help: "Model identifier sent to the provider." },
  { key: "media.adapters.openrouter.timeoutMs", type: "integer", tier: "advanced", help: "Upper bound for one generation, including polling, in milliseconds." },
  { key: "media.adapters.openrouter.maxConcurrent", type: "integer", tier: "advanced", help: "How many requests this adapter runs at once; further jobs wait." },
  { key: "media.adapters.replicate.enabled", type: "boolean", tier: "advanced", help: "Unset: on once `apiKeyRef` resolves to a secret. `false` keeps the adapter off whatever the key." },
  { key: "media.adapters.replicate.apiKeyRef", type: "string", tier: "advanced", help: "Name of the secret that holds the API key (a handle, never the key itself). Store the key with `plur1bus secret set <name>`, value on stdin." },
  { key: "media.adapters.replicate.baseUrl", type: "string", tier: "advanced", help: "Override the provider endpoint (an absolute http(s) URL, checked when the adapter is built). https only; plain http is accepted for loopback test servers." },
  { key: "media.adapters.replicate.model", type: "string", tier: "advanced", help: "Model identifier sent to the provider." },
  { key: "media.adapters.replicate.timeoutMs", type: "integer", tier: "advanced", help: "Upper bound for one generation, including polling, in milliseconds." },
  { key: "media.adapters.replicate.maxConcurrent", type: "integer", tier: "advanced", help: "How many requests this adapter runs at once; further jobs wait." },
  { key: "media.adapters.fal.enabled", type: "boolean", tier: "advanced", help: "Unset: on once `apiKeyRef` resolves to a secret. `false` keeps the adapter off whatever the key." },
  { key: "media.adapters.fal.apiKeyRef", type: "string", tier: "advanced", help: "Name of the secret that holds the API key (a handle, never the key itself). Store the key with `plur1bus secret set <name>`, value on stdin." },
  { key: "media.adapters.fal.baseUrl", type: "string", tier: "advanced", help: "Override the provider endpoint (an absolute http(s) URL, checked when the adapter is built). https only; plain http is accepted for loopback test servers." },
  { key: "media.adapters.fal.model", type: "string", tier: "advanced", help: "Model identifier sent to the provider." },
  { key: "media.adapters.fal.timeoutMs", type: "integer", tier: "advanced", help: "Upper bound for one generation, including polling, in milliseconds." },
  { key: "media.adapters.fal.maxConcurrent", type: "integer", tier: "advanced", help: "How many requests this adapter runs at once; further jobs wait." },
  { key: "media.adapters.together.enabled", type: "boolean", tier: "advanced", help: "Unset: on once `apiKeyRef` resolves to a secret. `false` keeps the adapter off whatever the key." },
  { key: "media.adapters.together.apiKeyRef", type: "string", tier: "advanced", help: "Name of the secret that holds the API key (a handle, never the key itself). Store the key with `plur1bus secret set <name>`, value on stdin." },
  { key: "media.adapters.together.baseUrl", type: "string", tier: "advanced", help: "Override the provider endpoint (an absolute http(s) URL, checked when the adapter is built). https only; plain http is accepted for loopback test servers." },
  { key: "media.adapters.together.model", type: "string", tier: "advanced", help: "Model identifier sent to the provider." },
  { key: "media.adapters.together.timeoutMs", type: "integer", tier: "advanced", help: "Upper bound for one generation, including polling, in milliseconds." },
  { key: "media.adapters.together.maxConcurrent", type: "integer", tier: "advanced", help: "How many requests this adapter runs at once; further jobs wait." },
  { key: "media.adapters.drawthings.enabled", type: "boolean", tier: "advanced", help: "Use Draw Things for image generation." },
  { key: "media.adapters.drawthings.host", type: "string", tier: "advanced", help: "Host of the Draw Things API. A host other than loopback also needs `allowLan`." },
  { key: "media.adapters.drawthings.port", type: "integer", tier: "advanced", help: "Port of the Draw Things API." },
  { key: "media.adapters.drawthings.allowLan", type: "boolean", tier: "advanced", help: "Allow a private-network host (LAN, Tailscale). The traffic is plain http and carries no key." },
  { key: "media.adapters.drawthings.model", type: "string", tier: "advanced", help: "Model file name as shown in Draw Things." },
  { key: "media.adapters.drawthings.timeoutMs", type: "integer", tier: "advanced", help: "Upper bound for one generation in milliseconds." },
  { key: "media.adapters.drawthings.maxConcurrent", type: "integer", tier: "advanced", help: "How many requests run at once; the app renders one at a time." },
  { key: "media.adapters.coreml.enabled", type: "boolean", tier: "advanced", help: "Use the Core ML helper for image generation." },
  { key: "media.adapters.coreml.binary", type: "string", tier: "advanced", help: "Absolute path of the `media-coreml` executable." },
  { key: "media.adapters.coreml.modelsDir", type: "string", tier: "advanced", help: "Directory with compiled Core ML model folders (split-einsum or original)." },
  { key: "media.adapters.coreml.model", type: "string", tier: "advanced", help: "Name of a model folder inside `modelsDir`." },
  { key: "media.adapters.coreml.computeUnits", type: "string", tier: "advanced", help: "Where inference runs. `auto` lets the helper choose from the model's attention variant (split-einsum: Neural Engine, original: GPU)." },
  { key: "media.adapters.coreml.scheduler", type: "string", tier: "advanced", help: "Diffusion scheduler name understood by the helper; unset uses the helper default." },
  { key: "media.adapters.coreml.timeoutMs", type: "integer", tier: "advanced", help: "Upper bound for one generation in milliseconds." },
];
