import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = join(here, "..", "schema", "rpc.schema.json");
const outDir = join(here, "..", "generated");
const schema = JSON.parse(readFileSync(schemaPath, "utf8"));

// 1. The schema itself must be a valid 2020-12 schema.
const ajv = new Ajv2020({ strict: true, allErrors: true, allowUnionTypes: true });
addFormats(ajv);
ajv.addKeyword("x-rpc-version");
ajv.addKeyword("x-stability");
ajv.addKeyword("x-since");
ajv.addKeyword("x-deprecated");
ajv.addKeyword("x-server");
if (!ajv.validateSchema(schema)) throw new Error(`rpc.schema.json is not a valid schema: ${ajv.errorsText()}`);

// 2. Method and notification names come from the schema, never from a hand list.
const methods = Object.keys(schema.$defs.methods);
const notifications = Object.keys(schema.$defs.notifications);
for (const [kind, defs] of [["method", schema.$defs.methods], ["notification", schema.$defs.notifications]]) {
  for (const [name, def] of Object.entries(defs)) {
    if (def["x-server"] !== "core" && def["x-server"] !== "supervisor") throw new Error(`rpc.schema.json: ${kind} ${name} lacks x-server core|supervisor`);
  }
}

// 3. Flatten methods/notifications into top-level $defs so the TS generator names them.
const flat = { ...schema, $defs: { ...schema.$defs } };
delete flat.$defs.methods; delete flat.$defs.notifications;
const pascal = (s) => s.split(/[.\-_]/).map((w) => w[0].toUpperCase() + w.slice(1)).join("");
for (const m of methods) {
  flat.$defs[`${pascal(m)}Params`] = schema.$defs.methods[m].params;
  flat.$defs[`${pascal(m)}Result`] = schema.$defs.methods[m].result;
}
for (const n of notifications) flat.$defs[`${pascal(n)}Notification`] = schema.$defs.notifications[n];
flat.type = "object"; flat.properties = {}; flat.additionalProperties = false; // root is a namespace only

let ts = await compile(flat, "RpcRoot", { bannerComment: "/* generated by @plur1bus/rpc-schema build.mjs — do not edit */", additionalProperties: false, strictIndexSignatures: true, unreachableDefinitions: true });
// The generator names a definition that is only a $ref (core.status → CoreStatus, jobs.run → JobRun) after its
// target alone; alias it so every method keeps its <PascalM>Params/<PascalM>Result pair.
for (const m of methods) {
  for (const [suffix, def] of [["Params", schema.$defs.methods[m].params], ["Result", schema.$defs.methods[m].result]]) {
    const name = `${pascal(m)}${suffix}`;
    const ref = Object.keys(def).length === 1 && typeof def.$ref === "string" ? def.$ref.match(/^#\/\$defs\/([A-Za-z0-9]+)$/)?.[1] : undefined;
    if (ref && !new RegExp(`^export (interface|type) ${name}\\b`, "m").test(ts)) ts += `export type ${name} = ${ref};\n`;
  }
}
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "types.ts"), ts);
writeFileSync(join(outDir, "names.json"), JSON.stringify({ rpc: schema["x-rpc-version"], methods, notifications, errors: schema.$defs.ErrorCode.enum }, null, 2));

// 4. Per-server capability fixtures (features: []), from the same buildCapabilities the core serves; the Rust
//    `plur1bus_rpc::capabilities` is tested against them. index.ts needs generated/names.json, written above.
const { buildCapabilities } = await import(pathToFileURL(join(here, "index.ts")).href);
const capDir = join(here, "..", "fixtures", "capabilities");
mkdirSync(capDir, { recursive: true });
for (const server of ["core", "supervisor"]) writeFileSync(join(capDir, `${server}.json`), JSON.stringify(buildCapabilities([], server), null, 2) + "\n");
console.log(`rpc-schema: ${methods.length} methods, ${notifications.length} notifications → generated/`);
